##########
# collectionbuilder-gh
# Jekyll Digital Collection Generator, designed for GitHub Pages
# https://github.com/CollectionBuilder/collectionbuilder-gh
##########

##########
# SITE SETTINGS
#
# title of site appears in banner
# title: Personal Website
# tagline, a short phrase that will appear throughout the site in the top banner
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
# description: "Website Description"
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
# author: "Sam Olson"
